apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timeapi-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timeapi-blue-green
        color: blue
    spec:
      containers:
        - name: timeapi
          image: gcr.io/fine-arbor-198904/timeapi:blue
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          ports:
            - containerPort: 8000
